# Generated by Django 6.0.1 on 2026-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefaText', models.CharField(verbose_name=255)),
                ('dificuldade', models.CharField(verbose_name=255)),
                ('dataConclusao', models.DateField()),
                ('dataCriacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
